DEFAULT_DG_SALT = 0.1
DEFAULT_DG_TEMP_CELSIUS = 60

DG_CONFIG_PARAM_SALT = 'salt'
DG_CONFIG_PARAM_TEMP = 'temp'

DefaultDGConfig = {
	DG_CONFIG_PARAM_SALT: DEFAULT_DG_SALT,
	DG_CONFIG_PARAM_TEMP: DEFAULT_DG_TEMP_CELSIUS
}