DEFAULT_TM_PROBE_CONCENTRATION = 2e-07
DEFAULT_TM_PRIMER_CONCENTRATION = 9e-07
DEFAULT_TM_SALT = 0.1

TM_CONFIG_PARAM_PROBE_CONC = 'probe_concentration'
TM_CONFIG_PARAM_PRIMER_CONC = 'primer_concentration'
TM_CONFIG_PARAM_SALT = 'salt'

DefaultTMConfig = {
	'probe_concentration': DEFAULT_TM_PROBE_CONCENTRATION,
	'primer_concentration': DEFAULT_TM_PRIMER_CONCENTRATION,
	'salt': DEFAULT_TM_SALT
}